### ISSUE TITLE
Which live ID?

### ISSUE THREAD

**Issue by marmarjohnson** [Schamper/xbox-remote-power#11]
I noticed the live-id the script reports is different than that you  find going through the xbox menus.  That reported by the script is missing the first the first byte (first 2 characters) but then seems to have two characters at the end, 0y, as a replacement.  The script does not work for me---although I'm trying it because of issues the xbox app has on turning on my xbox.   Is the script still working for people?

Finally, with people familiar how the xbox turn-on works, why would Microsoft have the following instructions to get the xbox app to work (following these instructions I can get by xbox to turn on/off using the app if I do it right after I turn it off---otherwise it s tops working):

Step 1
CLEAR PERSITENT STORAGE:
Goto Home > settings > disc and blue ray > Blu-ray > persistent storage > clear persistent storage. (Please do this three times
Step 2
CLEAR CONSOLE MAC ADDRESS:
Home > settings > network > advance settings > alternate MC address > clear > restart
Step 3 - this one scared the ***\* out of me but nothing bad happened.
DELETE PROFILE:
Settings>>Sign in, Security & Passkey>>and then select the option "Remove me from Xbox".
Step 4
POWER CYCLE:
Turn off console > unplug everything from the console > wait for 2 minutes and plug everything back > Turn On the console.
Step 5
DOWNLOAD PROFILE:
To download your profile once again, please click the "Avatar Icon">>>and then select the "Add New" option to re-download the profile.
Step 6
CONFIRM YOU HAVE AN OPEN NAT This one kind of ran for me but that may be because my NAT was open already.
Settings > Network > Test Multiplayer connection> (Do not select Continue or Select) > Use your Controller and at the same time both bumpers and triggers (It should be at the same time) > another test will run and It will open the NAT after.
Try the application and it should work.

**Comment by Schamper** [comment]
Yeah the way this script gets the Live ID is primitive and not how you're supposed to do it. It's best to just not use the "ping" feature at all, for the time being.

**Comment by Schamper** [comment]
Removed pinging for Live ID.
