### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by xrandalxflagg** [Schamper/xbox-remote-power#12]
hi
python complete noob here
but...
I get an invalid syntax when I even try to use the command alone without the xbox information.
Basically tried python 3, 3.1 and 3.5
pasting
python xbox-remote-power.py 
into the command line.
Am I doing it incorrectly?
I apologize if this is a basic question.
thanks

**Comment by JDQuackers** [comment]
Can you paste the error that you receive? It works on my end

**Comment by Schamper** [comment]
Works fine on 3.5.1, reopen when you get some useful information.

**Comment by xrandalxflagg** [comment]
sorry never saw it. I ended up just using xoon. thanks
