### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by kashjs** [Schamper/xbox-remote-power#16]
I truly appreciate your work here. This is the ONLY solution i have found that works without IR blaster. 

I am trying to create custom remote recipe on anymote app on ios. 
Is this just a simple TCP request? if so, can you send me an example raw request data. Also, Can you give me a little more detail on what exactly are you doing to turn on the xbox?

**Comment by Schamper** [comment]
It's a UDP datagram, and the code is only 80 lines... Surely you could figure it out yourself. The datagram is specific to your LiveID anyway.

Closing this as it isn't a real issue.
