### ISSUE TITLE
Ping works but power on doesn't

### ISSUE THREAD

**Issue by danielpatricio** [Schamper/xbox-remote-power#18]
Trying to figure out it if is a power setting configuration issue or something else. I am running the Xbox One S and power mode is set to instant-on.

Xbox app on my android seems to work for power on, when I run the script with my credentials and the Xbox on the ping succeeds.

However if it do it with the Xbox off it fails, even with retries for about 5 minutes.

Thanks for any help here, looking to integrate with Amazon Alexa to automate a couple more things around the house. @Schamper

**Comment by tmthyjames** [comment]
I'm having the same issue.

**Comment by vijayg78** [comment]
You need to set the Power mode to "instant-on". Then only the ip will be reachable. If this setting is "energy-saving" this will not work. I changed it and it worked flawlessly!

**Comment by JFriesenhahn** [comment]
Did anybody ever resolve this? I'm having the same issue in instant-on mode

--

Resolved -- I had this issue when I only had a passthrough for TCP 5050 on my router; adding a 5050 passthrough for UDP port 5050 as well fixed it.

**Comment by Schamper** [comment]
@JFriesenhahn yeah no TCP is involved in the "Smartglass" part of this. It's only used in game streaming.

**Comment by JFriesenhahn** [comment]
Thanks for the heads up, I was wondering why the ping worked at all

**Comment by uSravan** [comment]
Turning on Works great. How to turn off the console?

**Comment by jheiselman** [comment]
@uSravan [per this repository's maintainer, it is out of scope for this project](https://github.com/Schamper/xbox-remote-power/issues/19)

**Comment by Schamper** [comment]
@uSravan https://github.com/OpenXbox/xbox-smartglass-core-python

I'm closing this as it's not really an issue with the project but more with how the console works.
