### ISSUE TITLE
Enhancement Request: Add Power Off

### ISSUE THREAD

**Issue by jheiselman** [Schamper/xbox-remote-power#19]
I would like to be able to power off my Xbox One as well. I don't have the payload code needed to do this and I can't seem to find it documented anywhere.

**Comment by Schamper** [comment]
It's not possible with a simple payload code, you need to set up an active connection to the console. This is possible but out of scope for this project, so I'm closing this.

**Comment by Schamper** [comment]
https://github.com/OpenXbox/xbox-smartglass-core-python

**Comment by jheiselman** [comment]
Ooh. Interesting. Thanks.
