### ISSUE TITLE
Its not working from linux

### ISSUE THREAD

**Issue by log-box** [Schamper/xbox-remote-power#21]
Im using xbox-remote-power.sh
Live_ID a.y.log@outlook.com
IP 192.168.88.7 
Energy saving is off
But dosn`t work,

What im doing wrong ?

**Comment by log-box** [comment]
logbox@server:~/xbox-remote-power-master$ ./xbox-remote-power.sh
Sending power on packets to 192.168.88.7...
Xbox should turn on now, pinging to make sure...
Failed to ping Xbox :(
Do you wish to keep trying? (y/n): y
Sending power packets and pinging until Xbox is on...
...

**Comment by log-box** [comment]
logbox@server:~/xbox-remote-power-master$ cat xbox-remote-power.sh
#!/bin/bash

IP_ADDR=192.168.88.7
LIVE_ID=a.y.log@outlook.com

python xbox-remote-power.py -a $IP_ADDR -i $LIVE_ID

**Comment by Schamper** [comment]
You're supposed to take the Live ID from the Settings page of your Xbox One, not put in your Xbox Live account.

From the readme: `To find your Live device ID, go to Settings -> System -> Console info.`

**Comment by log-box** [comment]
Ooh!!!! its my bad... I thought that is LIVE ID. ITS WORKS!! Great thank YOU!
