### ISSUE TITLE
Remote Start on home network only

### ISSUE THREAD

**Issue by ghost** [Schamper/xbox-remote-power#23]
Hi,

This is a great little tool, thank you for writing it. I am trying to get the remote start to work when I am off of my home network. I have port forwarded 5050 on my router and have also assigned a static IP address (on both the Xbox and Router). I have bridged my modem with the router so I am not going to be doubled NAT'd. It doesn't work for some reason. I have also placed the Xbox in the DMZ and still it does not work. I am using a Linksys router, not sure where to go to from here?

Thx

**Comment by Schamper** [comment]
Sorry, can't help you with this.
