### ISSUE TITLE
Any chance of power off?

### ISSUE THREAD

**Issue by Flizzzard** [Schamper/xbox-remote-power#25]
Is is possible to not only send packets to power on, but also power off?

**Comment by tuxuser** [comment]
yeah it's possible (soon) :)

**Comment by Flizzzard** [comment]
Any idea how far off that might be? I know it's complex! Trying to avoid having to go down an IR-blaster route if there's a programmatic option...

**Comment by tuxuser** [comment]
Hopefully within the next 3 weeks

**Comment by Flizzzard** [comment]
@tuxuser - If it would help, I'm happy to provide some time to help test the new feature. Looking forward to it!

**Comment by Schamper** [comment]
https://github.com/OpenXbox/xbox-smartglass-core-python
