### ISSUE TITLE
Power Off

### ISSUE THREAD

**Issue by JohanPotgieter** [Schamper/xbox-remote-power#26]
Have you ever considered making another script to switch the Xbox One off? Do you know if it's possible. Any help would be appreciated.

Thanks,

PS. Script works great for me.

**Comment by Schamper** [comment]
This is possible, but vastly more complicated than what this script is doing since you'll need to setup an actual SmartGlass connection to the Xbox, and then send it the power off command. It's being worked on though.

**Comment by theoryav** [comment]
Have you been able to figure out how to do a SmartGlass connection?

**Comment by Schamper** [comment]
Yes ;)

**Comment by jzarca01** [comment]
Have you made any progress on the feature ?

**Comment by Schamper** [comment]
@jzarca01 yes. Something will be released soon-ish.

**Comment by Stesus** [comment]
@Schamper That is very exciting to hear

**Comment by ghost** [comment]
@Schamper What's the status on this feature?

**Comment by Schamper** [comment]
https://github.com/OpenXbox/xbox-smartglass-core-python
