### ISSUE TITLE
MAC address connectivity feature wanted

### ISSUE THREAD

**Issue by banzr** [Schamper/xbox-remote-power#27]
As many routers use DHCP to dynamically assign IP addresses, it would be nice to store the XBOX ONE MAC address in a configuration file to reliably link to the xbox's static address.

**Comment by bofh8** [comment]
arp -a | grep  94:9a:a9

**Comment by jheiselman** [comment]
Many routers will provide host name lookup for devices that get an IP via DHCP. The Xbox One uses a client ID of "XboxOne" meaning that, for most people, you should be able to use XboxOne in place of the IP address and it will work. I am doing this on my network with a LEDE (OpenWRT-compatible) router.
