### ISSUE TITLE
can this be used as third party addons on hass.io?

### ISSUE THREAD

**Issue by arissaraiva** [Schamper/xbox-remote-power#29]
Hello I´m using hass.io home assistant on a pi3, can his be installed as a third party addon? if not there is another way to use this?

**Comment by Schamper** [comment]
Yeah probably, not right out of the box though. Not sure how home assistant works exactly, but I'm certain it can be done.

**Comment by arissaraiva** [comment]
anyone have experience on how to use this on hass.io?

**Comment by scottdarby93** [comment]
I'm sure it will work with the python scripts function?
https://home-assistant.io/components/python_script/

**Comment by arissaraiva** [comment]
I´m trying here with some help of the forum in home assistant but it didn´t work yet, a guy is assisting me to use shell command [https://home-assistant.io/components/shell_command/](url) toghther with input boolean and an automation, I was able to set up the switch of the input boolean the aumation but it isn´t running the script and not sending any command to the xbox yet, anyone has knwloedge to help on this?

**Comment by alijaf123** [comment]
Can anybody help, I am trying to execute this script via exec binding but for some reason, I am unable to understand how to pass the IP and Live ID and I have tried several syntaxes but it looks like that Thing file isn't able to pass the arguments and then I am also not sure how to accept the output parameters.

Tried both for things
Things:
Thing exec:command:apc [command="/usr/share/openhab2/addons/xbox/xbox-remote-power.py -a <IP>, -i <Liveid>"]
Thing exec:command:apc [command="/usr/share/openhab2/addons/xbox/xbox-remote-power.py"]

if I am passing the argument in the first line then any idea what would be the Item code to accept and execute it?
