### ISSUE TITLE
Power down functionality

### ISSUE THREAD

**Issue by mateuszdrab** [Schamper/xbox-remote-power#32]
Hey

I found this script when looking for a feature for Home Assistant to power off XBox.

Is it possible to modify the script to allow sending a packet to turn off the console? 

I actually need that more than being able to turn it on remotely.

Thanks

**Comment by Ritty5** [comment]
Hi,

I think this is something they are already working on. Looking at closed issues #25  and #26 . The last comment on 28th December 2017 stating it is will be released soon-ish.

Regards,

James.

**Comment by mateuszdrab** [comment]
Oh true, I didn't notice that as those issues were closed.

Let's hope this happens and I'll try to turn this module into a home assistant component :)

**Comment by Ritty5** [comment]
I have submitted a pull request to add a ping feature so a program can check if it is on or off.

**Comment by Schamper** [comment]
https://github.com/OpenXbox/xbox-smartglass-core-python
