### ISSUE TITLE
Only Working Intermittently

### ISSUE THREAD

**Issue by johnestan** [Schamper/xbox-remote-power#33]
I'm not able to get this to work reliably. Sometimes it just wont run. It always works if I try it shortly after turn the console off, but if the console has been off for a while it doesn't always work. I have the console on "instant on" mode. Below is the code from a unsuccessful attempt. 

Johns-Air:~ John$ /Users/John/xbox-remote-power.sh ; exit;
Sending power on packets to 24.178.88.26...
Traceback (most recent call last):
  File "./xbox-remote-power.py", line 83, in <module>
    main()
  File "./xbox-remote-power.py", line 37, in main
    send_power(s, power_packet)
  File "./xbox-remote-power.py", line 62, in send_power
    s.send(data)
socket.error: [Errno 51] Network is unreachable
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Schamper** [comment]
Not really an issue of this project as it's mostly related to how the console handles this.
