### ISSUE TITLE
Powering Off

### ISSUE THREAD

**Issue by m1st0** [Schamper/xbox-remote-power#34]
Looking at line 36 of [xbox-remote-power.py](https://github.com/Schamper/xbox-remote-power/blob/master/xbox-remote-power.py):
`power_header = b'\xdd\x02\x00' + chr(len(power_payload)).encode() + b'\x00\x00'`

I've attempted to work out a power off code as yours matched the 0xDD02 for powering the console on in the complete OpenXbox/xbox-smartglass-core-python repo. For powering off that repo notes on line 212 of [enum.py](https://github.com/OpenXbox/xbox-smartglass-core-python/blob/master/xbox/sg/enum.py):
`PowerOff = 0x39`

Would the change be possible on your line 36 above on my system?  Please help with understanding what the _power_header_ would need to be to send a power off.

**Comment by Fredde87** [comment]
Interesting project that OpenXbox repo. I had a quick read through it but they say the only unencrypted command is the PowerOn command.

So in order to do the PowerOff, you'd need to do send the discovery command, retrieve a certificate etc to get a authentication token and then send the poweroff command in encrypted format. So a lot more advanced than this project.

Why not just use their python scripts instead? They seem to have it all working?

**Comment by Schamper** [comment]
@Fredde87 is right, turning off is much more complicated and way out of scope for this project - the OpenXbox project provides this.

**Comment by m1st0** [comment]
Thanks for looking into this.  The reasons for the PowerOff research here is due to an opportunity to use [Saiy](https://play.google.com/store/apps/details?id=ai.saiy.android&hl=en_US) to provide a voice command towards [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm) or even include a [IFTTT](https://ifttt.com/) Web call towards Tasker to shut off the XBox from my Android phone.  This would allow additional Python apps to be run on Android to control many items and automate them using Python in this manner with voice control from a central device.  Python isn't on my Android devices of course, but [QPython](http://www.qpython.com/) allows some Python scripts which the OpenXBox project may have too many dependencies for.  I hope to try nonetheless:

Saiy->Tasker Saiy plugin -> QPython tasker plugin -> XBox

or

Google Assistant -> IFTTT Assistant plugin -> QPython tasker plugin -> XBox

Of course there are other paths, but this was simpler to me to use voice commands from Google Assistant or Saiy.  I know I can just use the XBox app, or even use Saiy and Tasker possibly command that app, but I've built interactions like this where I can control things that aren't controllable by voice such as a Bluetooth lamp to completely be interactive to voice commands through the Saiy path above.  [JuiceSSH](https://juicessh.com/) also has Saiy plugins like Tasker that can allow voice automation further though Bash/Sh.
