### ISSUE TITLE
NSlookup issue - advice please

### ISSUE THREAD

**Issue by Slegnor** [Schamper/xbox-remote-power#36]
Hi, i had this working perfectly for months but my router blew up and I had to replace it, same brand but different model (prev Asus RT-N66U, now RT-AC66U_B1)

I've reconfigured port 5050 pointing to the Xbox One (10.0.0.15) but when I run the bat I get this message and then it doesn't power on:

![image](https://user-images.githubusercontent.com/11891577/53168426-80b10580-35d2-11e9-8d29-37396f5c6f6f.png)

If I NSlookup something online on the network, 10.0.0.4 for example, that works but anything offline throws that message.

Any ideas what may be causing this change?  Firewall issue, DNS?  I'm a bit stumped

**Comment by Ritty5** [comment]
What power options do you have set for the Xbox? For this to work it needs to be in one of the low power mode that allows for updates to install, otherwise it turns off completely.

On the new router have you set a static IP for you Xbox?

**Comment by Slegnor** [comment]
I've figured it out thanks to your comment re low power mode.

Everything was configured correctly as before, what I had forgotten was the
power cut we had which will have powered the xbox off completely.
Just booted and it did the long cold boot then shut down as normal, now bat
works fine

Thanks for the assist
