### ISSUE TITLE
How to turn off the XBOX??

### ISSUE THREAD

**Issue by TUNA-NOPE** [Schamper/xbox-remote-power#41]
How to turn off the XBOX??
ן know the torn on msg is -
        power_payload = b'\x00' + chr(len(live_id)).encode() + live_id.upper() + b'\x00'
        power_header = b'\xdd\x02\x00' + chr(len(power_payload)).encode() + b'\x00\x00'
        power_packet = power_header + power_payload

Can anyone tell me how to turn off the Xbox ???

**Comment by OffBind** [comment]
i was wondering the same as im making a third party xbox access software
but i think its not possible

**Comment by Schamper** [comment]
Take a look at https://openxbox.org
