### ISSUE TITLE
not working on the new dashboard?

### ISSUE THREAD

**Issue by steve51184** [Schamper/xbox-remote-power#5]
is there an update planned or is it totally blocked?

**Comment by Schamper** [comment]
Funny, the day that the NXOE publicly released I got a lot of reports from people that it worked again/still. It was broken in the preview. It looks like it's kind of a hit and a miss, turning it on from a SmartGlass app is also unreliable for me. 

I'm not sure what is causing it to not work but I'll keep an eye out.

**Comment by derfreimann** [comment]
Yep, same here, but if you try often enough it will work eventually! It's like you say, the smartglass/xbox app faces the same issue. Besides that I noticed that my Xbox sometimes takes way too long powering on even though quick boot is enabled...

I modified the code a little bit for me to know if the boot process was successful by letting the script ping the xbox after trying to boot and if it all worked as planned it answers with a readout from the live id. If it didn't work it asks you to try again!

**Comment by Schamper** [comment]
@derfreimann nice! Would you like to submit that as a pull request? I think its a useful addition to the script.

**Comment by derfreimann** [comment]
I'll try later tonight (have to "re-englishize" it first, since I translated it to german for my very own convenience ;D).

But please be aware that I have no real clue about python, so it may all a bit whacky (but hey, it works! ;] )

**Comment by TimoVerbrugghe** [comment]
Hi everyone!

Did some own testing at home: as already mentioned, after a few tries the xbox would turn on (for me, around 5-6 times pushing the same command to my server will do). When I then open streaming f.e., shut down the xbox and immediately start up the script again, the xbox will always turn on. The xbox will then always turn on for the next 5 minutes or so after shutdown. After that, I need to retry a few times again.

So it seems that the xbox is maybe going into an even lower-powered state requiring multiple wakeup packets or something to turn on again... weird.

**Comment by jsphonorio** [comment]
Im also having an aissue turning back on after some time off or in standby. That addition  you made @derfreimann would be nice to see.

**Comment by derfreimann** [comment]
I created a pull request (I think)...

**Comment by jsphonorio** [comment]
Yes just saw it after I posted. Nice little change and I wrapped the whole thing in a while command to try a few. Still not working for me. It worked for me, then I let the box go into standby(ate lunch and didnt turn it off) and since then I havent been able  to get it back up.

**Comment by derfreimann** [comment]
That happened to me once too. Only solution was a soft reset of the Xbox (hold poer button for ~10 seconds while Xbox is on). Since the latest update it has a few flaws... hopefully a patch will follow soon!

**Comment by Schamper** [comment]
No pull request yet. You should go to the branch with your modifications (should be [this one](https://github.com/derfreimann/xbox-remote-power/tree/derfreimann-pingcheck-1)?) and there should be a button to create a pull request.

**Comment by derfreimann** [comment]
Tried again, hope it worked now.
I also implemented the WHILE loop jsphonorio mentioned the other day, trying to boot for a couple of hundred times. nice :D ...no more button mashing xD

**Comment by derfreimann** [comment]
Received an update yesterday (os version 10.0.10586.1024) - tried booting it remotely today and the while loop only needed one retry! Maybe even the initial boot worked already but because of the latency I only received the confirmation after the second try. Any of the ways, that's a new record :D

Maybe the update fixed some bugs!? ...or was it just a lucky punch?

**Comment by Schamper** [comment]
Interesting to hear. You could probably test it by trying to turning it on a couple hours after it's been turned off. From my experience it works fine right after having been turned off but usually doesn't after it's been off for a while.

**Comment by derfreimann** [comment]
Tried again now and changed time.sleep to 3 seconds to compensate the latency, now it seems to work flawlessly (still/yet).
Positive response at the first boot attempt ^^

**Comment by Schamper** [comment]
Doesn't seem to be an issue with this script but with the feature in general. (e.g. [recent Reddit thread about the issue](http://www.reddit.com/r/xboxone/comments/45o3my/tech_can_no_longer_turn_on_xbox_one_via/).

**Comment by Hanfrey** [comment]
Maybe MS changed something? I noticed that its not working on my iphone all the time, only sometimes. But on the Win10 XBOX App is working directly.
